sky:


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456


  redis:
    host: localhost
    port: 6379
    database: 1


  wechat:
    appid: wx229c0491ac2d11c0
    secret: 0f66187d8a9c5de76d25f5aefe9bda77


